#
# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: BSD-3-Clause
#

# The west manifest file (west.yml) for npmx-zephyr.

manifest:
  defaults:
    remote: nrfconnect

  remotes:
    - name: NordicSemiconductor
      url-base: https://github.com/NordicSemiconductor
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: npmx
      path: modules/npmx
      revision: 0ac6e7806e19e89af0d5dd909dd4ca353cd9f2bd
    - name: zephyr
      revision: v3.3.0
      import: true
      remote: zephyrproject
    - name: sdk-nrfxlib
      remote: nrfconnect
      revision: bb42c9c169177ff96b5f5b055b6c087679bfdcd3
      path: modules/nrfxlib
