# The west manifest file (west.yml) for npmx-zephyr.

manifest:
  defaults:
    remote: NordicSemiconductor

  remotes:
    - name: NordicSemiconductor
      url-base: https://github.com/NordicSemiconductor
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      revision: v3.3.0
      import: true
      remote: zephyrproject
    - name: npmx
      path: modules/npmx
      revision: b3036928e0b5b31912b295ea3ecbea913a726580
